stages:
  - test

before_script:
  - cd code/server
  - npm install

test_server:
  stage: test
  image: node:latest
  script:
    - set NODE_ENV=test
    - npm test --testPathPattern='(test_unit|test_integration)'
  rules:
    - if: $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "testdelivery" || $CI_COMMIT_BRANCH == "v2-base"
