version: '3'

services:
  client:
    build:
      context: ./code/client
    ports:
      - "3000:3000"
    networks:
      - ezelectronics-network
  server:
    build:
      context: ./code/server
    ports:
      - "3001:3001"
    volumes:
      - ./code/server/src/db:/app/src/db
    networks:
      - ezelectronics-network

networks:
  ezelectronics-network:
    driver: bridge
